### ISSUE TITLE
Need to determine how creative white points should be implemented.

### ISSUE THREAD

**Issue by KevinJW** [ampas/aces-vwg-output-transforms#10]
We need to evaluate how creative white points could be used, e.g. D60 in a D65 output, etc.

**Comment by KevinJW** [comment]
Related to this, 
 - need to check how white adaptation 'works' @alexfry volunteered

**Comment by scottdyer** [comment]
In the CTL, when the limiting white and encoding white are set to different chromaticities, the XYZ values of [1, 1, 1] for each white point are used to determine the scaling needed to bring the largest channel down to fit within 1.0. 

For D60sim in D65, this scalar is reasonable. 

In D60sim or D65sim in DCI, the scaling can get quite large. In v1.x of these transforms there was also an extra roll-off applied to make the scale required smaller, but I could not find an easy way to derive when such a roll-off should kick in and how to divide the amount that each is contributing to the necessary outcome of lowering the largest channel to fit within 1.0. Therefore, only the scale is used, and so there might be a noticeable darkening of the image in the DCI versions that "sim" another white point in the DCI white. This will be explained in documentation as a reason people should really just calibrate to P3-D65 or P3-D60 and use that ODT.

The scale is applied in the opposite direction on the inverse path.
