### ISSUE TITLE
Need to try select a single choice for dealing with scene values that lie beyond the models. 

### ISSUE THREAD

**Issue by KevinJW** [ampas/aces-vwg-output-transforms#13]
Currently we have:

1. compression mode
2. LMS matrix options
3. linear extension
4. ...

We should remember that straightening out the lines too much will result in us not really using the CAM.

**Comment by nick-shaw** [comment]
Have we definitely settled on compress mode (combined with a custom LMS matrix, the exact coefficients of which which may not yet be finalised)?

**Comment by priikone** [comment]
The compress mode seems to have some invertibility issues I've noticed.  They may be related to the changes we've made to avoid NaNs/Infs or it maybe just the algorithm itself.  Not sure, unfortunately I still have no clear grasp on how it actually works...

**Comment by priikone** [comment]
But I suppose the overall idea is to do effectively gamut compression.  Maybe some other algo could be tried as well.  Jed certainly did a lot of work on this (https://github.com/jedypod/nuke-colortools/blob/master/toolsets/chromaticity/GamutCompressCLin.nk is very simple chromaticity linear compressor).

**Comment by priikone** [comment]
What if we just clamped the input to 0?  Isn't that what ACES1 does as well?  We're trying to handle all these crazy values out there, most of which is just noise, with a complicated algorithm, that perhaps isn't needed at all.  I quickly tested this with compress mode disabled (and with Thomas's CAM16 primaries) and everything looks nice.  In fact, in many cases looks better than nice, better than with the compress mode (there will be some skew).  This included images like Red christmas and the Blue bar and other problematic images.  And there is always RGC for those rare cases (and they really would be _rare_ with the current ACES2 candidate) that may prove problematic.  Thoughts?

**Comment by nick-shaw** [comment]
The release (CTL [Developer Release](https://community.acescentral.com/t/aces-v2-developer-release/5427)) clamps input to AP1.
