### ISSUE TITLE
RGB Offset/colour shift difference between Hellwig and ZCam on grey scale ramp

### ISSUE THREAD

**Issue by KevinJW** [ampas/aces-vwg-output-transforms#3]
As reported by Pekka when feeding a pure grey RAMP onto both models we see a slight colour difference.

Thoughts are to look for a matrix that doesn't quite row sum to 1, or an extra CAM, etc.

Kevin

**Comment by KevinJW** [comment]
As reported by @nick-shaw 

When turning on/off highlight desat we see a break in Hellwig 2022, independent of the choice of tonescale curve.

The choice of curve does shift the location the break occurs at

Gamut compression and focus bypass also trigger differences 

![image](https://user-images.githubusercontent.com/1186170/202311366-f9de1172-8028-4aae-8451-c8459b8db70c.png)

**Comment by KevinJW** [comment]
After some investigation we noted that surround illuminant adaptation appears to be one cause of the colour bias as would be expected when the surround does not match the input white point.

**Comment by nick-shaw** [comment]
The plot above is using the "live from params" LMS matrix, which exaggerates the effect. Turning off gamut compression (which should be doing nothing with a neutral ramp) removes the break, but shows how wonky the curves really are.

<img width="1792" alt="Screenshot 2022-11-17 at 10 02 23" src="https://user-images.githubusercontent.com/12493652/202578943-6e1ab3b8-0662-4005-a168-9ca9cb298d3f.png">

**Comment by thomasmansencal** [comment]
What are the curves here? The red one not being monotonic is quite something!

**Comment by nick-shaw** [comment]
Linear ramp -> ACEScct to ACES. v23 from @alexfry repo. Settings as in the screenshot. I would like to know if others see the same or it’s my system.

**Comment by KevinJW** [comment]
See also https://community.acescentral.com/t/aces-2-0-cam-drt-development/4700/14

**Comment by priikone** [comment]
Yes, @nick-shaw, I see the same thing with "Live from params", but I never use it typically.  I don't see that craziness with the red channel with "Stock" params.

**Comment by alexfry** [comment]
I think I've fixed this in v024

Looks like the issue was related to the variable "discount_illuminant" vs "discountIlluminant"

**Comment by KevinJW** [comment]
The discontinuity occurs when HK mode was on 'in the middle' solution is don't do that.
