### ISSUE TITLE
Replacing iterative solve for gamut hull calculation?

### ISSUE THREAD

**Issue by KevinJW** [ampas/aces-vwg-output-transforms#6]
Can we invent a direct hull calculation rather than solve iteratively solve as this will help with performance and inversion.

**Comment by KevinJW** [comment]
Plot gamut hulls as a set of points and try fit a minimum volume ellipsoid and see if there is  close enough fit.

**Comment by priikone** [comment]
There's also Björn's gamut approximation.  I used it in OkishDRT.

https://colab.research.google.com/drive/1rYFDmHuv0MNzCHXQSwhBkJaMbTQzoXl3?usp=sharing

**Comment by KevinJW** [comment]
As part of the discussion on 11/01/23 Alex and Pekka offered to try some different approaches for parts of the problem hopping to show something at the next meeting.

**Comment by KevinJW** [comment]
In this weeks meeting we had two demonstrations showing how the gamut hull could be approximated as well as an exploration of the point raised https://community.acescentral.com/t/aces-2-0-cam-drt-development/4700/112 

Whilst the visualisation tools helped further work is needed to better understand the overall "flow" of the movement caused by the gamut mapping and how the true hull interacts with the various stages of the whole mapping.

**Comment by priikone** [comment]
This was done in v030.

**Comment by KevinJW** [comment]
Winning
