### ISSUE TITLE
Choice of LMS primaries

### ISSUE THREAD

**Issue by KevinJW** [ampas/aces-vwg-output-transforms#8]
we need to decide on the LMS primary matrix and then document the derivation.

**Comment by scottdyer** [comment]
These settled on an LMS matrix derived from a modified version of the CAM16 primaries - specifically with the blue value changed.

The primaries used are:
```
const Chromaticities CAM16_PRI = 
{
    { 0.8336,  0.1735 },
    { 2.3854, -1.4659 },
    { 0.087 , -0.125  },
    { 0.333 ,  0.333  }
};
