### ISSUE TITLE
v24 locks up if you disable GPU priority

### ISSUE THREAD

**Issue by KevinJW** [ampas/aces-vwg-output-transforms#9]
Some of my team were testing out v24 in Nuke and noted that if you disable GPU priority it appears to lock up Nuke.

tested on 2 different Cent OS 7.9 machines

This is probably minor, so just for the record.

Kevin

**Comment by nick-shaw** [comment]
The iterative solves are so processor intensive, it is hard to know if this is genuinely a lock-up or whether it would finish eventually if you waited long enough. It takes quite some time on the GPU, so I imagine the time on the CPU would be huge!

The Blink will not compile for the GPU on my M1 Mac, so I tried turning the GPU off on the smaller kernel used in the group node for plotting. This does compile for the CPU. I have set the full DRT compiling for the CPU and am still waiting…

**Comment by KevinJW** [comment]
More recent testing on a Windows machine with an Intel IGPU shows the blink doesn't finish compiling, tested on Nuke 14.
